### PR TITLE
Fully delegate installation to rstantools

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates your package to fully delegate the installation/compilation of stan models to rstantools. I've also added a github actions R CMD CHECK workflow to make sure that changes are compatible across all platforms

### CODE REVIEW

**Comment by andrjohns** [comment]
Would you be able to merge this PR and release to CRAN? We're aiming to submit a new release of rstan soon

**Comment by mlysy** [comment]
Hi, my recollection is that I did things this way so as not to have to depend on **rstantools**, i.e., I set up the package with `rstantools::use_rstan(auto_config = FALSE)`.  Is there a compelling reason for me to reconsider this decision?  Or would it be sufficient for me to rerun the `use_rstan()` and `rstan_config()` with the latest version of **rstantools**?

**Comment by andrjohns** [comment]
The issue is that your current structure means that your package will only be compatible with the versions of `rstan` and `StanHeaders` that were installed when your model code (the `src` folder) was generated. 

As `rstan`/`StanHeaders` is updated, there are changes to the c++ that gets generated from a given stan model and changes to the compilation/linker flags that are used to compile this. By using `rstantools` with the `configure` scripts, the c++ and the needed `Makevars` are re-generated at installation. This means that your package will always be compatible with changes/updates to `rstan` and `StanHeaders`

**Comment by mlysy** [comment]
OK, you've convinced me.

One question regarding your PR.  I take it that most of the changes in it could have been made by running `rstantools::use_rstan(auto_config = TRUE)`.  My recollection is that this triggers the line `Biarch: true` to be added to the `DESCRIPTION` file.  Is that the case?  I.e., would it be possible to check whether running that command does not meaningfully alter your PR except by adding `Biarch: true`?

**Comment by andrjohns** [comment]
The process is the same. The `Biarch: true` option simply forces the building for both 32-bit and 64-bit Windows (already the default behaviour, but forced). Your package will currently build for both windows architectures, and R will soon stop building for 32-bit windows (currently only done for `oldrel`), so the option is no longer relevant

**Comment by andrjohns** [comment]
How does that all sound to you? Would you be able to merge and submit soon, if possible?

**Comment by mlysy** [comment]
Sounds good.

**Pull request merged**
